os: linux
group: edge

addons:
  apt:
    packages:
    - libdevmapper-dev

language: rust

matrix:
    allow_failures:
        # Allow beta tasks to fail
        - rust: beta
    include:
        - rust: stable
          env: TASK=travis_fmt
        - rust: stable
          env: TASK=build
        - rust: stable
          env: TASK=build
          install:
            - rustup default 1.31.0
        - rust: stable
          sudo: required
          env: TASK=sudo_test
        - rust: stable
          before_script:
              - rustup component add clippy
          env: TASK=clippy
        # Run tests on rust beta, in order to be good Rustaceans
        - rust: beta
          sudo: required
          env: TASK=sudo_test

branches:
    only: master

script: make -f Makefile $TASK 
