os: linux
group: edge

addons:
  apt:
    packages:
    - libdevmapper-dev

language: rust

matrix:
    fast_finish: true
    allow_failures:
        # Allow beta tasks to fail
        - rust: beta
    include:
        - rust: stable
          env: TASK=travis_fmt
        - rust: stable
          env: TASK=build
        # Build on lowest supported compiler version
        - rust: 1.31.0
          env: TASK=build
        - rust: stable
          sudo: required
          env: TASK=sudo_test
        # Run clippy using the compiler version recommended for development
        - rust: 1.31.0
          before_script:
              - rustup component add clippy
          env: TASK=clippy
        # Run tests on rust beta, in order to be good Rustaceans
        - rust: beta
          sudo: required
          env: TASK=sudo_test

branches:
    only: master

script: make -f Makefile $TASK 
