os: linux
dist: trusty
group: edge

addons:
  apt:
    packages:
    - libdevmapper-dev

language: rust

matrix:
    allow_failures:
        - env: TASK=clippy
    include:
        - rust: stable
          env: TASK=fmt
        - rust: stable
          env: TASK=build
        - rust: stable
          sudo: required
          env: TASK=sudo_test
        - rust: nightly
          env: TASK=clippy

branches:
    only: master

script: make -f Makefile $TASK 
