language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose && cargo test --verbose
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    ( cargo build --verbose --features clippy &&
      cargo test --verbose --features clippy )
