[package]
name = "devicemapper"
version = "0.1.0"
authors = ["Andy Grover <agrover@redhat.com>"]
description = "A library for using Linux device mapper"
documentation = "http://agrover.github.io/devicemapper-rs/doc/devicemapper/index.html"
# homepage = "..."
repository = "https://github.com/agrover/devicemapper-rs"
readme = "README.md"
keywords = ["Linux", "device", "mapper", "libdm"]
license = "MPL-2.0"


[dependencies]
libc = "*"
byteorder = "*"
nix = "*"
